apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-api
  namespace: hypertheory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: support-api
  template:
    metadata:
      labels:
        app: support-api
    spec:
      containers:
      - name: support-api
        image: jeffrygonzalez/support-api-aug-2024:v15
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
