apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-api-path
  labels:
    name: support-api-path
spec:
  rules:
  - host: progressive.com/services/support
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: support-api-service
            port: 
              number: 80
